apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullrays-indoor-wireless-twin.name" . }}
  labels:
    {{- include "fullrays-indoor-wireless-twin.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations: {{- include "fullrays-indoor-wireless-twin.product-info" . | indent 4 }}
data:
  logcontrol.json: |-
    [
      {
        "severity": "info",
        "container": "fullrays-indoor-wireless-twin"
      }
    ]
