apiVersion: v2
appVersion: "2.0.0"
description: An rApp with a PostgreSQL database
name: rapp-devcon-database-demo-app
type: application
version: 8.7.6-6
dependencies:
  - name: postgresql-ha
    version: "16.0.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql-ha.enabled