apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullrays-indoor-wireless-twin.name" . }}-postgresql-secret
  labels:
    {{- include "fullrays-indoor-wireless-twin.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
    {{- include "fullrays-indoor-wireless-twin.product-info" . | indent 4 }}
type: Opaque
data:
  postgres-password: {{ index .Values "postgresql-ha-credentials" "postgresql" "password" | b64enc | quote }}
  password: {{ index .Values "postgresql-ha-credentials" "postgresql" "password" | b64enc | quote }}
  repmgr-password: {{ index .Values "postgresql-ha-credentials" "postgresql" "repmgrPassword" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullrays-indoor-wireless-twin.name" . }}-pgpool-secret
  labels:
    {{- include "fullrays-indoor-wireless-twin.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
    {{- include "fullrays-indoor-wireless-twin.product-info" . | indent 4 }}
type: Opaque
data:
  admin-password: {{ index .Values "postgresql-ha-credentials" "pgpool" "adminPassword" | b64enc | quote }}
  sr-check-password: {{ index .Values "postgresql-ha-credentials" "postgresql" "password" | b64enc | quote }}
