apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-hello-world-python-app.name" . }}-postgresql-secret
  labels:
    {{- include "eric-oss-hello-world-python-app.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
    {{- include "eric-oss-hello-world-python-app.product-info" . | indent 4 }}
type: Opaque
data:
  postgres-password: {{ index .Values "postgresql-ha-credentials" "postgresql" "password" | b64enc | quote }}
  password: {{ index .Values "postgresql-ha-credentials" "postgresql" "password" | b64enc | quote }}
  repmgr-password: {{ index .Values "postgresql-ha-credentials" "postgresql" "repmgrPassword" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-hello-world-python-app.name" . }}-pgpool-secret
  labels:
    {{- include "eric-oss-hello-world-python-app.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
    {{- include "eric-oss-hello-world-python-app.product-info" . | indent 4 }}
type: Opaque
data:
  admin-password: {{ index .Values "postgresql-ha-credentials" "pgpool" "adminPassword" | b64enc | quote }}
  sr-check-password: {{ index .Values "postgresql-ha-credentials" "postgresql" "password" | b64enc | quote }} 