apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullrays-indoor-wireless-twin.name" . }}
  labels:
    {{- include "fullrays-indoor-wireless-twin.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
{{- include "fullrays-indoor-wireless-twin.product-info" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fullrays-indoor-wireless-twin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
